// UUID: e45a4f74-15b5-4bbf-8ec7-981d35570a2d
// Generated by InSprint Automation
import { BasePage } from "./basePage";
import { Locator, Page } from "@playwright/test";

export class SalesforceLoginPage extends BasePage {
  private readonly usernameFieldSelector = "#username";
  private readonly passwordFieldSelector = "#password";
  private readonly loginButtonSelector = "#Login";
  private readonly homeTab = "a[title='Home']";

  constructor(page: Page) {
    super(page);
  }

  async enterUsername(username: string): Promise<void> {
    try {
      await this.page.fill(this.usernameFieldSelector, username);
      this.logInfo(`Entered username: ${username}`);
    } catch (error) {
      this.logError(`Failed to enter username: ${error}`);
      throw error;
    }
  }

  async isLoginPageReady(): Promise<boolean> {
    return this.page.isVisible(this.usernameFieldSelector);
  }

  async enterPassword(password: string): Promise<void> {
    try {
      await this.page.fill(this.passwordFieldSelector, password);
      this.logInfo(`Entered password: ${password}`);
    } catch (error) {
      this.logError(`Failed to enter password: ${error}`);
      throw error;
    }
  }

  async clickLoginButton(): Promise<void> {
    try {
      await this.page.click(this.loginButtonSelector);
      this.logInfo("Clicked login button");
    } catch (error) {
      this.logError(`Failed to click login button: ${error}`);
      throw error;
    }
  }

  async isHomeTabVisible(): Promise<boolean> {
    try {
      const isVisible = await this.page.isVisible(this.homeTab);
      this.logInfo("HomeTab is successfully displayed");
      return isVisible;
    } catch (error) {
      this.logError(`Failed to check dashboard visibility: ${error}`);
      throw error;
    }
  }

  // async getDashboardText(): Promise<string> {
  //   try {
  //     const text = await this.page.textContent(this.dashboardSelector);
  //     this.logInfo(`Dashboard text retrieved: ${text}`);
  //     return text || "";
  //   } catch (error) {
  //     this.logError(`Failed to retrieve dashboard text: ${error}`);
  //     throw error;
  //   }
  // }
}
