// UUID: 5b7bc4b0-7b7c-44c0-be54-4a671f534947
// Generated by InSprint Automation
import { Given, When, Then } from "@cucumber/cucumber";
import { expect } from "@playwright/test";
import { CustomWorld } from "../support/custom-world";
import { SalesforceLoginPage } from "../pages/salesforce-login-page";
import config from "../config/config";

Given(
  "I am on the Salesforce login page {string}",
  async function (this: CustomWorld, url: string) {
    const loginPage = this.getPageObject(SalesforceLoginPage);
    await loginPage.navigateTo(config.baseUrl);
    await expect(
      this.page!.locator(loginPage.usernameFieldSelector)
    ).toBeVisible();
  }
);

When(
  "I enter my User Name as {string} in the username field",
  async function (this: CustomWorld, username: string) {
    const loginPage = this.getPageObject(SalesforceLoginPage);
    await loginPage.enterUsername(config.credentials.username);
  }
);

When(
  "I enter my Password as {string} in the password field",
  async function (this: CustomWorld, password: string) {
    const loginPage = this.getPageObject(SalesforceLoginPage);
    await loginPage.enterPassword(config.credentials.password);
  }
);

When(
  "I click the {string} button",
  async function (this: CustomWorld, buttonName: string) {
    const loginPage = this.getPageObject(SalesforceLoginPage);
    await loginPage.clickLoginButton();
  }
);

Then(
  "I should be successfully logged into the Salesforce Sandbox environment",
  async function (this: CustomWorld) {
    const loginPage = this.getPageObject(SalesforceLoginPage);
    const isDashboardVisible = await loginPage.isDashboardVisible();
    expect(isDashboardVisible).toBeTruthy();
  }
);

Then(
  "I should see the Salesforce dashboard or homepage",
  async function (this: CustomWorld) {
    const loginPage = this.getPageObject(SalesforceLoginPage);
    const dashboardText = await loginPage.getDashboardText();
    expect(dashboardText).toContain("Welcome");
  }
);
